Replace old Travis CI by GitHub action
OCR-D/ocrd_kraken pull request #41
Opened 2023-09-23 17:58 UTC by stweil

This includes some smaller improvements and compatibility fixes for the Makefile.

2023-09-23 18:03 UTC, stweil commented
See the [current action results](https://github.com/stweil/ocrd_kraken/actions) in my fork.

2023-10-13 16:00 UTC, kba requested changes

2023-10-13 18:55 UTC, stweil commented on Makefile
> +ifeq ($(shell uname -s), Darwin)
Sorry, that was a copy+paste error. `make deps-ubuntu` is also used in the Dockerfile.

I now implemented a different check for `/usr/bin/apt-get` which should cover not only macOS but also Linux distributions without apt.

2023-10-15 14:43 UTC, kba approved these changes

2023-10-15 14:44 UTC, kba commented on Makefile
> +ifeq ($(shell uname -s), Darwin)
Thanks, that is a better solution.

2023-10-15 14:44 UTC, merged